name: Python Package Test

on: 
  push:
    branches: ["main", "dev"]
  pull:
    branches: ["main", "dev"]

  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true 

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag sc-testing-service

    - name: Execute Docker Compose file
      run: |
        docker-compose up
/authorize/bitbucket
    - name: Upload Output Logs
      uses: actions/upload-artifact@v3
      with:
        name: output-logs
        path: output-logs

    - name: Shutdown Docker Compose file
      run: |
        docker-compose down

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
        name: output-logs

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-ubuntu-18.04-python-3.6.9
        path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
        parallel: true

  coveralls:
    name: Coveralls
    needs: build
    runs-on: ubuntu-18.04
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
